### ISSUE TITLE
To get statistics from a farm of Asterisk boxes

### ISSUE THREAD

**Issue by beneditomarques** [litnimax/asterisk-stats#3]
Hi,

I have a farm of Asterisk boxes behind Kamailio server, and Queues is in realtime. All Asterisks see the same queues and agents, and the state devices is distributed via corosync. I’ve notice that the same queue has different statistics values in each asterisk box.  Is there any way to get statistics summarized using asterisk-stats?

**Comment by litnimax** [comment]
Hi!
I dont think Asterisk Queues are capable to share the stats our of the box. 
Sorry.
